# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Coral Sr/Ca Calibration - An Example from Dry Tortugas 
author: Deborah Khider
logo: coral_logo.jpg

# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Information about where the book exists on the web
repository:
  url: https://github.com/khider/dry-tortugas-calibration-fun  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering    : true   # Continuous numbering across parts/chapters